################################################################################
#
# barebox-boot
#
################################################################################

BAREBOX_BOOT_VERSION = $(BAREBOX_VERSION)
BAREBOX_BOOT_SITE = $(BAREBOX_SITE)
BAREBOX_BOOT_SITE_METHOD = $(BAREBOX_SITE_METHOD)
BAREBOX_BOOT_SOURCE = $(BAREBOX_SOURCE)
BAREBOX_BOOT_DEPENDENCIES = $(BAREBOX_DEPENDENCIES)
BAREBOX_BOOT_LICENSE = $(BAREBOX_LICENSE)
BAREBOX_BOOT_LICENSE_FILES = $(BAREBOX_LICENSE_FILES)
BAREBOX_BOOT_POST_PATCH_HOOKS += $(BAREBOX_POST_PATCH_HOOKS)
BAREBOX_BOOT_MAKE_FLAGS = $(BAREBOX_MAKE_FLAGS)
BAREBOX_BOOT_MAKE_ENV = $(BAREBOX_MAKE_ENV)
BAREBOX_BOOT_INSTALL_IMAGES = $(BAREBOX_INSTALL_IMAGES)

ifeq ($(BR2_TARGET_BAREBOX_USE_DEFCONFIG),y)
BAREBOX_BOOT_SOURCE_CONFIG = $(BAREBOX_BOOT_DIR)/arch/$(BAREBOX_ARCH)/configs/$(call qstrip,\
	$(BR2_TARGET_BAREBOX_BOARD_DEFCONFIG))_defconfig
else ifeq ($(BR2_TARGET_BAREBOX_USE_CUSTOM_CONFIG),y)
BAREBOX_BOOT_SOURCE_CONFIG = $(call qstrip,$(BR2_TARGET_BAREBOX_CUSTOM_CONFIG_FILE))
endif

BAREBOX_BOOT_KCONFIG_FILE = $(BAREBOX_BOOT_SOURCE_CONFIG)
BAREBOX_BOOT_KCONFIG_FRAGMENT_FILES = $(BAREBOX_KCONFIG_FRAGMENT_FILES)
BAREBOX_BOOT_KCONFIG_EDITORS = $(BAREBOX_KCONFIG_EDITORS)
BAREBOX_BOOT_KCONFIG_OPTS = $(BAREBOX_MAKE_FLAGS)

ifeq ($(BR2_TARGET_BAREBOX_BAREBOXENV),y)
define BAREBOX_BOOT_BUILD_BAREBOXENV_CMDS
	$(TARGET_CC) $(TARGET_CFLAGS) $(TARGET_LDFLAGS) -o $(@D)/bareboxenv \
		$(@D)/scripts/bareboxenv.c
endef
endif

ifeq ($(BR2_TARGET_BAREBOX_CUSTOM_ENV),y)
BAREBOX_BOOT_ENV_NAME = $(notdir $(call qstrip,\
	$(BR2_TARGET_BAREBOX_CUSTOM_ENV_PATH)))
define BAREBOX_BOOT_BUILD_CUSTOM_ENV
	$(@D)/scripts/bareboxenv -s \
		$(call qstrip, $(BR2_TARGET_BAREBOX_CUSTOM_ENV_PATH)) \
		$(@D)/$(BAREBOX_BOOT_ENV_NAME)
endef
define BAREBOX_BOOT_INSTALL_CUSTOM_ENV
	cp $(@D)/$(BAREBOX_BOOT_ENV_NAME) $(BINARIES_DIR)
endef
endif

define BAREBOX_BOOT_BUILD_CMDS
	$(BAREBOX_BOOT_BUILD_BAREBOXENV_CMDS)
	$(TARGET_MAKE_ENV) $(MAKE) $(BAREBOX_BOOT_MAKE_FLAGS) -C $(@D)
	$(BAREBOX_BOOT_BUILD_CUSTOM_ENV)
endef

define BAREBOX_BOOT_INSTALL_IMAGES_CMDS
	if test -h $(@D)/barebox-flash-image ; then \
		cp -L $(@D)/barebox-flash-image $(BINARIES_DIR)/barebox.bin ; \
	else \
		cp $(@D)/barebox.bin $(BINARIES_DIR);\
	fi
	$(BAREBOX_BOOT_INSTALL_CUSTOM_ENV)
endef

ifeq ($(BR2_TARGET_BAREBOX_BAREBOXENV),y)
define BAREBOX_BOOT_INSTALL_TARGET_CMDS
	cp $(@D)/bareboxenv $(TARGET_DIR)/usr/bin
endef
endif

# Checks to give errors that the user can understand
# Must be before we call to kconfig-package
ifeq ($(BR2_TARGET_BAREBOX)$(BR_BUILDING),yy)
ifeq ($(BAREBOX_BOOT_SOURCE_CONFIG),)
$(error No Barebox config file. Check your BR2_TARGET_BAREBOX_BOARD_DEFCONFIG or BR2_TARGET_BAREBOX_CUSTOM_CONFIG_FILE settings)
endif
endif

$(eval $(kconfig-package))
