################################################################################
#
# barebox-xload
#
################################################################################

BAREBOX_XLOAD_VERSION = $(BAREBOX_VERSION)
BAREBOX_XLOAD_SITE = $(BAREBOX_SITE)
BAREBOX_XLOAD_SITE_METHOD = $(BAREBOX_SITE_METHOD)
BAREBOX_XLOAD_SOURCE = $(BAREBOX_SOURCE)
BAREBOX_XLOAD_DEPENDENCIES = $(BAREBOX_DEPENDENCIES)
BAREBOX_XLOAD_LICENSE = $(BAREBOX_LICENSE)
BAREBOX_XLOAD_LICENSE_FILES = $(BAREBOX_LICENSE_FILES)
BAREBOX_XLOAD_POST_PATCH_HOOKS += $(BAREBOX_POST_PATCH_HOOKS)
BAREBOX_XLOAD_MAKE_FLAGS = $(BAREBOX_MAKE_FLAGS)
BAREBOX_XLOAD_MAKE_ENV = $(BAREBOX_MAKE_ENV)
BAREBOX_XLOAD_INSTALL_IMAGES = $(BAREBOX_INSTALL_IMAGES)
BAREBOX_XLOAD_INSTALL_DEST = $(BINARIES_DIR)/$(call qstrip,$(BR2_TARGET_BAREBOX_XLOAD_INSTALL_FILENAME))

ifeq ($(BR2_TARGET_BAREBOX_XLOAD_USE_DEFCONFIG),y)
BAREBOX_XLOAD_SOURCE_CONFIG = $(BAREBOX_XLOAD_DIR)/arch/$(BAREBOX_ARCH)/configs/$(call qstrip,\
	$(BR2_TARGET_BAREBOX_XLOAD_BOARD_DEFCONFIG))_defconfig
else ifeq ($(BR2_TARGET_BAREBOX_XLOAD_USE_CUSTOM_CONFIG),y)
BAREBOX_XLOAD_SOURCE_CONFIG = $(call qstrip,$(BR2_TARGET_BAREBOX_XLOAD_CUSTOM_CONFIG_FILE))
endif

BAREBOX_XLOAD_KCONFIG_FILE = $(BAREBOX_XLOAD_SOURCE_CONFIG)
BAREBOX_XLOAD_KCONFIG_FRAGMENT_FILES = $(BAREBOX_KCONFIG_FRAGMENT_FILES)
BAREBOX_XLOAD_KCONFIG_EDITORS = $(BAREBOX_KCONFIG_EDITORS)
BAREBOX_XLOAD_KCONFIG_OPTS = $(BAREBOX_MAKE_FLAGS)

define BAREBOX_XLOAD_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) $(BAREBOX_XLOAD_MAKE_FLAGS) -C $(@D)
endef

define BAREBOX_XLOAD_INSTALL_IMAGES_CMDS
	if test -h $(@D)/barebox-flash-image ; then \
		cp -L $(@D)/barebox-flash-image $(BAREBOX_XLOAD_INSTALL_DEST) ; \
	else \
		cp $(@D)/barebox.bin $(BAREBOX_XLOAD_INSTALL_DEST);\
	fi
endef

$(eval $(kconfig-package))
